import React from 'react'
import Icon from '@ant-design/icons';
import LogoRestaurantSVG from './SVGcode/LogoSVG';
import MailSVG from './SVGcode/MailSVG';
import LockSVG from './SVGcode/LockSVG';
import GreyMailSVG from './SVGcode/FadedMail';
import SidedLogoSVG from './SVGcode/SidedLogo';
import PieChartSVG from './SVGcode/PieChart';
import HouseLogoSVG from './SVGcode/HouseLogo';
import UserIconSVG from './SVGcode/UserIconSVG';
import VectorSVG from './SVGcode/VectorSVG';
import SlidersSVG from './SVGcode/SlidersSVG';
import SmileyFaceSVG from './SVGcode/SmileyFaceSVG';
import BucketSVG from './SVGcode/BucketSVG';
import BinSVG from './SVGcode/BinSVG';
import GreyBinSVG from './SVGcode/GreyBinSVG';
import EditIconSVG from './SVGcode/EditIconSVG';

export const LogoRestaurantIcon = (props) => <Icon component={LogoRestaurantSVG} {...props} />;
export const MailIcon = (props) => <Icon component={MailSVG} {...props} />;
export const GreyMailIcon = (props) => <Icon component={GreyMailSVG} {...props} />;
export const LockIcon = (props) => <Icon component={LockSVG} {...props} />;
export const SidedLogoIcon = (props) => <Icon component={SidedLogoSVG} {...props} />;
export const PieChartIcon = (props) => <Icon component={PieChartSVG} {...props} />;
export const HouseIcon = (props) => <Icon component={HouseLogoSVG} {...props} />;
export const UserIcon = (props) => <Icon component={UserIconSVG} {...props} />;
export const VectorIcon = (props) => <Icon component={VectorSVG} {...props} />;
export const SlidersIcon = (props) => <Icon component={SlidersSVG} {...props} />;
export const SmileyFaceIcon = (props) => <Icon component={SmileyFaceSVG} {...props} />;
export const BucketIcon = (props) => <Icon component={BucketSVG} {...props} />;
export const BinIcon = (props) => <Icon component={BinSVG} {...props} />;
export const GreyBinIcon = (props) => <Icon component={GreyBinSVG} {...props} />;
export const EditIcon = (props) => <Icon component={EditIconSVG} {...props} />;